apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  namespace: userapi
spec:
  selector:
    matchLabels:
      run: userapi
  replicas: 1
  template:
    metadata:
      labels:
        run: userapi
    spec:
      containers:
      - name: userapi
        image: davidogbiko/fastuserapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
