---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.appName }}
  namespace: {{ .Values.deployment.appName }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.deployment.appName }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        run: {{ .Values.deployment.appName }}
    spec:
      containers:
      - name: {{ .Values.deployment.appName }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        env:
          - name: "DATABASE_URL"
            valueFrom:
              secretKeyRef:
                key: database
                name: {{ .Values.deployment.appName }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
...
