---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.appName }}
  namespace: {{ .Values.deployment.appName }}
  labels:
    run: {{ .Values.deployment.appName }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    run: {{ .Values.deployment.appName }}
...

