image:
  repository: davidogbiko/fastuserapi
  version: 0.0.1
  pullPolicy: IfNotPresent

deployment:
  appName: userapi
  replicas: 1

service:
  type: NodePort
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

database: database
