name: Build UserAPI Image
on:
  push:
    paths:
      - user_api/**
      - .github/workflows/build_image.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Lint with flake8
        run: |
          flake8 ./user_api --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ./user_api --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Test with pytest
        run: |
          pytest user_api/test_main.py -v

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - uses: docker/login-action@v1
        name: Login to Dockerhub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./user_api
          push: true
          tags: |
            davidogbiko/fastuserapi:${{ github.sha }}
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'davidogbiko/fastuserapi:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
