name: Deploy UserAPI
on:
  push:
    paths:
      - .github/workflows/deploy.yaml
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-userapi:
    name: Deploy UserAPI
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v3
        id: install
          
      - name: Deploy UserAPI
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
          DATABASE_URL: '${{ secrets.DATABASE_URL }}'
        run: helm upgrade --install userapi --set database=$DATABASE_URL--set image.tag=${{ github.sha }} ./kubernetes/helm -n userapi

      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0
